import { Link } from 'react-router-dom'
import SectionHeading from '../components/SectionHeading'

const education = [
  ['Bachelor of Engineering', 'Computer Science and Engineering', 'KLE Technological University, Hubli', 'Nov 2022 – Present', 'CGPA: 9.23', 'Hubli, India'],
  ['Pre-University', '', 'SRA Composite PU College, Banhatti', 'Sept 2020 – Apr 2022', 'Percentage: 97.17%', 'Bagalkot, India'],
  ['SSLC', '', 'SRA High School, Banhatti', 'June 2020', 'Percentage: 97.44%', 'Bagalkot, India'],
]
const certificates = [['NPTEL – Programming in Java', 'NPTEL', 'Programming in Java', 'N'], ['Juniper Networks Certified Associate', 'Juniper Networks', 'Junos (JNCIA-Junos)', 'J']]

function CodeWindow() { return <div className="code-window relative overflow-hidden rounded-2xl border border-cyan-300/30 bg-[#08122a]/90 p-5 shadow-2xl shadow-cyan-950/40"><div className="mb-5 flex gap-2"><i className="h-2.5 w-2.5 rounded-full bg-pink-400" /><i className="h-2.5 w-2.5 rounded-full bg-amber-300" /><i className="h-2.5 w-2.5 rounded-full bg-cyan-300" /></div><p className="font-mono text-xs leading-7 text-cyan-100"><span className="text-violet-300">function</span> <span className="text-cyan-300">buildSolutions</span>() {'{' }<br />&nbsp;&nbsp;<span className="text-violet-300">const</span> passion = <span className="text-emerald-300">&quot;code&quot;</span>;<br />&nbsp;&nbsp;<span className="text-violet-300">const</span> goal = <span className="text-emerald-300">&quot;impact&quot;</span>;<br /><br />&nbsp;&nbsp;<span className="text-violet-300">while</span> (learning) {'{' }<br />&nbsp;&nbsp;&nbsp;&nbsp;improve();<br />&nbsp;&nbsp;&nbsp;&nbsp;build();<br />&nbsp;&nbsp;&nbsp;&nbsp;solve();<br />&nbsp;&nbsp;{'}'}<br />{'}'}<span className="code-cursor" /></p><div className="absolute -bottom-8 -right-6 h-24 w-24 rounded-full bg-violet-500/30 blur-2xl" /></div> }

export default function About() { return <div className="reveal"><div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><SectionHeading eyebrow="About me" title="Building reliable software with curiosity and care.">I’m Tejashwini Godyal, a Computer Science and Engineering student at KLE Technological University, Hubli. I enjoy building practical software solutions, working with backend and web technologies, and exploring AI/ML and computer vision.</SectionHeading><p className="max-w-2xl leading-7 text-slate-600 dark:text-slate-300">Through my Software Development Internship at Dvara Solutions, I contributed to the Munify Funding Platform across backend APIs, dashboard workflows, business logic, frontend-backend integration, and data migration. I enjoy solving real-world problems and building clean, reliable software.</p></div><CodeWindow /></div><div className="mt-20 grid gap-6 lg:grid-cols-2"><article className="glass-card rounded-2xl border border-cyan-300/20 p-7"><div className="section-card-title"><span>◈</span><h2>Education</h2></div><div className="timeline mt-7">{education.map(([degree, major, school, date, score, place]) => <div key={degree} className="timeline-item relative pb-8 pl-7 last:pb-0"><i /><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="font-display text-lg font-semibold text-slate-950 dark:text-white">{degree}</h3><span className="date-badge">{date}</span></div>{major && <p className="mt-1 text-sm font-medium text-cyan-700 dark:text-cyan-300">{major}</p>}<p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{school}</p><p className="mt-2 text-sm font-semibold text-violet-700 dark:text-violet-300">{score}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{place}</p></div>)}</div></article><article className="glass-card rounded-2xl border border-cyan-300/20 p-7"><div className="section-card-title"><span>✦</span><h2>Certifications</h2></div><div className="mt-7 space-y-4">{certificates.map(([title, issuer, detail, initial]) => <div key={title} className="cert-card flex items-start gap-4 rounded-xl border border-cyan-300/15 bg-white/50 p-4 dark:bg-white/5"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-violet-400/15 font-bold text-violet-600 dark:text-violet-300">{initial}</div><div><h3 className="font-semibold text-slate-950 dark:text-white">{title}</h3><p className="mt-1 text-sm text-cyan-700 dark:text-cyan-300">{issuer}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{detail}</p></div></div>)}</div><Link to="/certifications" className="mt-7 inline-flex text-sm font-bold text-cyan-700 transition hover:text-violet-600 dark:text-cyan-300">View certifications →</Link></article></div></div> }
