import { useState } from 'react'
import SectionHeading from '../components/SectionHeading'
import Icon from '../components/Icons'
import { profile } from '../data/profile'

export default function Contact() {
  const [status, setStatus] = useState('')
  const submit = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (!form.get('name') || !form.get('email') || !form.get('message')) return setStatus('Please complete every field.'); setStatus('Thanks — this form is a front-end preview. Please email me directly to get in touch.'); event.currentTarget.reset() }
  const contactLink = 'flex items-center gap-3 rounded-lg py-1 transition hover:opacity-70'
  return <div className="reveal"><SectionHeading eyebrow="Contact" title="Let’s build something useful.">I’m happy to connect about software development, web development, and AI/ML opportunities.</SectionHeading><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><aside className="rounded-2xl bg-slate-950 p-7 text-white dark:bg-indigo-400 dark:text-slate-950"><p className="font-display text-2xl font-semibold">Reach out directly.</p><div className="mt-8 space-y-4 text-sm"><a className={contactLink} href={`mailto:${profile.email}`}><Icon name="mail" size={18} /><span><span className="mb-1 block text-xs uppercase tracking-widest opacity-60">Email</span>{profile.email}</span></a><a className={contactLink} href={profile.linkedin} target="_blank" rel="noreferrer"><Icon name="linkedin" size={18} /><span><span className="mb-1 block text-xs uppercase tracking-widest opacity-60">LinkedIn</span>tejashwini-godyal-b39b91287 ↗</span></a><a className={contactLink} href={profile.github} target="_blank" rel="noreferrer"><Icon name="github" size={18} /><span><span className="mb-1 block text-xs uppercase tracking-widest opacity-60">GitHub</span>Tejashwini1385 ↗</span></a></div></aside><form onSubmit={submit} noValidate className="rounded-2xl border border-slate-200 bg-white p-7 dark:border-white/10 dark:bg-white/5"><label className="block text-sm font-bold">Name<input name="name" required className="mt-2 w-full rounded-xl border border-slate-200 bg-transparent px-4 py-3 font-normal outline-none focus:border-indigo-500 dark:border-white/15" placeholder="Your name" /></label><label className="mt-5 block text-sm font-bold">Email<input name="email" type="email" required className="mt-2 w-full rounded-xl border border-slate-200 bg-transparent px-4 py-3 font-normal outline-none focus:border-indigo-500 dark:border-white/15" placeholder="you@example.com" /></label><label className="mt-5 block text-sm font-bold">Message<textarea name="message" required rows="4" className="mt-2 w-full resize-y rounded-xl border border-slate-200 bg-transparent px-4 py-3 font-normal outline-none focus:border-indigo-500 dark:border-white/15" placeholder="Tell me a little about the opportunity." /></label>{status && <p className="mt-4 text-sm text-indigo-600 dark:text-indigo-300" role="status">{status}</p>}<button className="mt-6 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-indigo-500" type="submit">Send message</button></form></div></div>
}
