import { Link } from 'react-router-dom'
import { profile } from '../data/profile'
import { useProjects } from '../hooks/useProjects'
import ProjectCard from '../components/ProjectCard'
import Icon, { ArrowUpRight } from '../components/Icons'
import TypingRole from '../components/TypingRole'

export default function Home() {
  const { data: projects } = useProjects()
  const socialClass = 'inline-flex items-center gap-1.5 hover:text-cyan-300'

  return <>
    <section className="relative isolate overflow-hidden py-8 sm:py-16"><div className="grid-bg absolute inset-0 -z-10" /><div className="reveal max-w-4xl"><p className="mb-5 inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-xs font-bold tracking-wide text-indigo-700 dark:border-indigo-400/20 dark:bg-indigo-400/10 dark:text-indigo-200">OPEN TO SOFTWARE & AI/ML OPPORTUNITIES</p><h1 className="font-display text-5xl font-semibold leading-[1.02] tracking-[-.055em] text-slate-950 sm:text-7xl dark:text-white">Hi, I’m <span className="text-indigo-600 dark:text-indigo-300">Tejashwini Godyal.</span></h1><p className="mt-5 text-xl font-semibold text-cyan-700 dark:text-cyan-300">Computer Science Engineer <span className="mx-1 text-violet-500">&amp;</span> Software Developer</p><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl dark:text-slate-300">I build practical software solutions and explore AI/ML-driven technologies as a <TypingRole />.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/projects" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-indigo-600 dark:bg-indigo-400 dark:text-slate-950">View my work <ArrowUpRight /></Link><a href="/Tejashwini_Nityanand_Godyal.pdf" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold text-slate-800 transition hover:border-indigo-400 hover:text-indigo-600 dark:border-white/20 dark:text-white dark:hover:text-indigo-200"><Icon name="folder" />View resume <ArrowUpRight /></a></div><div className="mt-9 flex flex-wrap gap-5 text-sm font-semibold text-slate-600 dark:text-slate-300"><a className={socialClass} href={profile.github} target="_blank" rel="noreferrer"><Icon name="github" />GitHub</a><a className={socialClass} href={profile.linkedin} target="_blank" rel="noreferrer"><Icon name="linkedin" />LinkedIn</a><a className={socialClass} href={`mailto:${profile.email}`}><Icon name="mail" />Email</a></div></div></section>
    <section className="mt-16 overflow-hidden rounded-3xl border border-cyan-300/25 bg-slate-950 p-7 text-white shadow-xl shadow-cyan-950/10 sm:p-10 dark:bg-[#0b1728]"><div className="grid gap-8 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-cyan-300">Featured internship project</p><h2 className="mt-4 max-w-2xl font-display text-3xl font-semibold sm:text-5xl">Municipal Funding Platform <span className="text-cyan-300">(Munify)</span></h2><p className="mt-4 max-w-xl leading-7 text-slate-300">Software Development Intern · Dvara Solutions Pvt Ltd</p><p className="mt-4 max-w-xl text-sm leading-7 text-slate-300">A web-based platform for municipal project funding, approvals, documents, monitoring, and workflow coordination.</p></div><Link to="/projects/munify" className="inline-flex w-fit items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-slate-950 transition hover:bg-cyan-300">View case study <ArrowUpRight /></Link></div></section>
    <section className="metric-grid mt-16 grid gap-3 border-y border-slate-200 py-8 sm:grid-cols-3 dark:border-white/10"><div><p>9.23</p><span>CGPA</span></div><div><p>Software Development</p><span>Internship · Dvara Solutions</span></div><div><p>AI / ML</p><span>Research & computer vision</span></div></section>
    <section className="py-20"><div className="mb-9 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-indigo-600 dark:text-indigo-300">Selected work</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">Projects with purpose.</h2></div><Link to="/projects" className="text-sm font-bold text-indigo-600 dark:text-indigo-300">View all projects <ArrowUpRight /></Link></div><div className="grid gap-5 md:grid-cols-3">{projects?.filter((project) => !project.featured).map((project) => <ProjectCard key={project.title} project={project} />)}</div></section>
  </>
}
