import { Link } from 'react-router-dom'
import { profile, skillGroups } from '../data/profile'
import { useProjects } from '../hooks/useProjects'
import ProjectCard from '../components/ProjectCard'
import Icon, { ArrowUpRight } from '../components/Icons'

function NeuralOrb() {
  const nodes = [[50, 7], [82, 28], [88, 64], [61, 88], [22, 78], [9, 42], [39, 35], [64, 48], [38, 64]]
  return <div className="relative mx-auto hidden aspect-square w-full max-w-[360px] lg:block" aria-hidden="true"><div className="absolute inset-[13%] rounded-full border border-cyan-300/25 animate-[spin_18s_linear_infinite]" /><div className="absolute inset-[25%] rounded-full border border-violet-300/30 animate-[spin_12s_linear_infinite_reverse]" /><div className="absolute inset-[37%] rounded-full bg-gradient-to-br from-cyan-300/30 via-blue-500/10 to-violet-500/30 blur-xl animate-pulse" /><div className="absolute inset-[34%] grid place-items-center rounded-full border border-cyan-300/40 bg-[#0b1836]/80 font-display text-sm font-bold tracking-[.25em] text-cyan-200 shadow-[0_0_35px_rgba(34,211,238,.25)]">AI</div><svg viewBox="0 0 100 100" className="absolute inset-0 h-full w-full overflow-visible">{nodes.map(([x, y], index) => nodes.slice(index + 1).filter((_, nextIndex) => (index + nextIndex) % 3 === 0).map(([x2, y2]) => <line key={`${index}-${x2}`} x1={x} y1={y} x2={x2} y2={y2} stroke="rgba(103,232,249,.25)" strokeWidth=".45" />))}{nodes.map(([x, y], index) => <circle key={`${x}-${y}`} cx={x} cy={y} r={index % 3 === 0 ? 2.1 : 1.25} fill={index % 3 === 0 ? '#a78bfa' : '#67e8f9'} className="animate-pulse" />)}</svg></div>
}

export default function Home() {
  const { data: projects } = useProjects()
  const socialClass = 'inline-flex items-center gap-1.5 hover:text-cyan-300'
  const selectedProjects = projects?.slice(0, 3)
  return <>
    <section className="relative isolate overflow-hidden py-10 sm:py-20"><div className="grid-bg absolute inset-0 -z-10" /><div className="grid items-center gap-12 lg:grid-cols-[1.25fr_.75fr]"><div className="max-w-3xl text-center lg:text-left"><p className="mb-5 inline-flex rounded-full border border-cyan-300/25 bg-cyan-400/10 px-3 py-1 text-xs font-bold tracking-wide text-cyan-700 dark:text-cyan-200">OPEN TO SOFTWARE &amp; AI/ML OPPORTUNITIES</p><h1 className="animate-[reveal_.7s_ease-out] font-display text-5xl font-bold leading-[.95] tracking-[-.06em] text-slate-100 sm:text-7xl">Tejashwini</h1><p className="mt-6 flex flex-wrap justify-center gap-x-3 gap-y-1 font-display text-lg font-semibold text-cyan-300 sm:text-xl lg:justify-start"><span>Full-Stack Developer</span><span className="text-violet-400">|</span><span>AI/ML Engineer</span><span className="text-violet-400">|</span><span>Software Engineer</span></p><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl dark:text-slate-300">Building <span className="font-semibold text-cyan-700 dark:text-cyan-300">scalable</span>, <span className="font-semibold text-blue-700 dark:text-blue-300">intelligent applications</span> that connect modern <span className="font-semibold text-violet-700 dark:text-violet-300">full-stack development</span> with <span className="font-semibold text-cyan-700 dark:text-cyan-300">AI</span> and <span className="font-semibold text-violet-700 dark:text-violet-300">machine learning</span>.</p><p className="mt-6 font-mono text-sm text-cyan-700 dark:text-cyan-200">&lt; Turning ideas into intelligent solutions /&gt;</p><div className="mt-9 flex flex-wrap justify-center gap-3 lg:justify-start"><a href="/Tejashwini_Nityanand_Godyal.pdf" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-slate-950 transition hover:-translate-y-0.5 hover:bg-cyan-300">View resume <ArrowUpRight /></a><Link to="/projects" className="inline-flex items-center gap-2 rounded-xl border border-cyan-300/35 bg-cyan-400/5 px-5 py-3 text-sm font-bold text-slate-800 transition hover:-translate-y-0.5 hover:border-cyan-300 dark:text-white">Explore projects <ArrowUpRight /></Link></div><div className="mt-9 flex flex-wrap justify-center gap-5 text-sm font-semibold text-slate-600 lg:justify-start dark:text-slate-300"><a className={socialClass} href={profile.github} target="_blank" rel="noreferrer"><Icon name="github" />GitHub</a><a className={socialClass} href={profile.linkedin} target="_blank" rel="noreferrer"><Icon name="linkedin" />LinkedIn</a><a className={socialClass} href={`mailto:${profile.email}`}><Icon name="mail" />Email</a></div></div><NeuralOrb /></div></section>

    <section id="about" className="scroll-mt-24 py-20"><div className="grid gap-7 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-700 dark:text-cyan-300">About me</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl dark:text-white">Practical software, grounded in fundamentals.</h2><p className="mt-5 max-w-2xl leading-8 text-slate-600 dark:text-slate-300">I&apos;m Tejashwini Godyal, a Computer Science and Engineering student at KLE Technological University, Hubli. I build practical software solutions across backend and web technologies while exploring AI/ML and computer vision.</p><p className="mt-4 max-w-2xl leading-7 text-slate-600 dark:text-slate-300">My Software Development Internship at Dvara Solutions gave me hands-on experience with backend APIs, dashboard workflows, business logic, integration, and data migration.</p><Link to="/about" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-cyan-700 hover:text-violet-600 dark:text-cyan-300">View more <ArrowUpRight /></Link></div><article className="rounded-2xl border border-cyan-300/20 bg-white/70 p-6 dark:bg-white/5"><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-700 dark:text-violet-300">Education</p><h3 className="mt-3 font-display text-xl font-semibold text-slate-950 dark:text-white">B.E. Computer Science and Engineering</h3><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">KLE Technological University, Hubli</p><div className="mt-5 flex items-center justify-between border-t border-cyan-300/15 pt-4"><span className="text-sm font-semibold text-cyan-700 dark:text-cyan-300">CGPA: 9.3</span><span className="text-xs text-slate-500 dark:text-slate-400">Nov 2022 – Present</span></div><div className="mt-5 flex flex-wrap gap-2">{['Backend development', 'Web technologies', 'AI / ML', 'Computer vision'].map((item) => <span key={item} className="rounded-full bg-cyan-400/10 px-3 py-1 text-xs font-medium text-cyan-800 dark:text-cyan-200">{item}</span>)}</div></article></div></section>

    <section id="projects" className="scroll-mt-24 border-y border-slate-200 py-20 dark:border-white/10"><div className="mb-9 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-700 dark:text-cyan-300">Selected projects</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">Work with real-world focus.</h2></div><Link to="/projects" className="inline-flex items-center gap-2 text-sm font-bold text-cyan-700 hover:text-violet-600 dark:text-cyan-300">View all projects <ArrowUpRight /></Link></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{selectedProjects?.map((project) => <ProjectCard key={project.title} project={project} />)}</div></section>

    <section id="skills" className="scroll-mt-24 py-20"><div className="grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-700 dark:text-cyan-300">Skills</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-tight text-slate-950 dark:text-white">A balanced technical toolkit.</h2><p className="mt-4 leading-7 text-slate-600 dark:text-slate-300">Programming, full-stack development, AI/ML, data, cloud, and modern engineering tools.</p><Link to="/skills" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-cyan-700 hover:text-violet-600 dark:text-cyan-300">Explore skills <ArrowUpRight /></Link></div><div className="grid gap-3 sm:grid-cols-2">{skillGroups.slice(0, 4).map((group) => <article key={group.title} className="rounded-2xl border border-cyan-300/15 bg-white/70 p-5 dark:bg-white/5"><h3 className="font-display font-semibold text-slate-950 dark:text-white">{group.title}</h3><div className="mt-4 flex flex-wrap gap-2">{group.skills.slice(0, 5).map((skill) => <span key={skill} className="rounded-lg bg-cyan-400/10 px-2.5 py-1.5 text-xs font-medium text-slate-700 dark:text-slate-200">{skill}</span>)}</div></article>)}</div></div></section>

    <section id="experience" className="scroll-mt-24 grid gap-5 border-y border-slate-200 py-20 md:grid-cols-2 dark:border-white/10"><article className="rounded-2xl border border-cyan-300/20 bg-white/70 p-6 dark:bg-white/5"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-700 dark:text-cyan-300">Experience</p><h2 className="mt-3 font-display text-2xl font-semibold text-slate-950 dark:text-white">Software Development Intern</h2><p className="mt-2 font-medium text-violet-700 dark:text-violet-300">Dvara Solutions Pvt Ltd · Jan 2026 – May 2026</p><p className="mt-4 leading-7 text-slate-600 dark:text-slate-300">Contributed to the Munify Funding Platform across FastAPI APIs, dashboard workflows, business logic, integration, and data migration.</p><Link to="/experience" className="mt-6 inline-flex text-sm font-bold text-cyan-700 hover:text-violet-600 dark:text-cyan-300">View experience →</Link></article><article className="rounded-2xl border border-violet-300/20 bg-white/70 p-6 dark:bg-white/5"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-700 dark:text-violet-300">Certifications</p><h2 className="mt-3 font-display text-2xl font-semibold text-slate-950 dark:text-white">Verified learning milestones.</h2><ul className="mt-4 space-y-2 text-sm leading-6 text-slate-600 dark:text-slate-300"><li>NPTEL – Programming in Java</li><li>Juniper Networks Certified Associate – Junos</li></ul><Link to="/certifications" className="mt-6 inline-flex text-sm font-bold text-cyan-700 hover:text-violet-600 dark:text-cyan-300">View certifications →</Link></article></section>

    <section id="contact" className="scroll-mt-24 py-20 text-center"><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-700 dark:text-cyan-300">Contact</p><h2 className="mt-3 font-display text-3xl font-semibold text-slate-950 dark:text-white">Let&apos;s build something meaningful.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-slate-600 dark:text-slate-300">I&apos;m always open to collaboration, opportunities, and interesting projects.</p><Link to="/contact" className="mt-7 inline-flex items-center gap-2 rounded-xl border border-cyan-300/35 bg-cyan-400/5 px-5 py-3 text-sm font-bold text-cyan-700 transition hover:border-cyan-300 hover:bg-cyan-400/10 dark:text-cyan-200">Get in touch <ArrowUpRight /></Link></section>
  </>
}
