import { NavLink } from 'react-router-dom'
import { useState } from 'react'
import ThemeToggle from './ThemeToggle'
import Icon from './Icons'
const links = [['/', 'Home', 'home'], ['/about', 'About', 'user'], ['/experience', 'Experience', 'briefcase'], ['/projects', 'Projects', 'folder'], ['/skills', 'Skills', 'code'], ['/contact', 'Contact', 'mail']]
export default function Navbar() {
  const [open, setOpen] = useState(false)
  const linkClass = ({ isActive }) => `nav-link inline-flex items-center gap-1.5 rounded-md px-2 py-1.5 text-xs font-medium transition ${isActive ? 'is-active bg-cyan-400/10 text-cyan-300' : 'text-slate-400 hover:bg-white/5 hover:text-cyan-200'}`
  const handleHome = () => window.dispatchEvent(new Event('portfolio:load-home'))
  return <header className="sticky top-0 z-50 border-b border-cyan-300/10 bg-[#080d24]/80 backdrop-blur-xl"><nav className="mx-auto flex h-16 max-w-6xl items-center px-5 lg:px-8" aria-label="Main navigation"><NavLink to="/" onClick={handleHome} className="group flex shrink-0 items-center" aria-label="Tejashwini home"><span className="tg-logo grid h-8 w-8 place-items-center rounded-lg font-display text-xs font-black text-slate-950">TG</span></NavLink><div className="ml-auto hidden items-center gap-2 lg:flex"><div className="flex items-center gap-1">{links.map(([to, label, icon]) => <NavLink key={to} to={to} onClick={to === '/' ? handleHome : undefined} className={linkClass}><Icon name={icon} size={14} />{label}</NavLink>)}</div><div className="ml-3 border-l border-cyan-300/15 pl-4"><ThemeToggle /></div></div><div className="ml-auto flex items-center gap-2 lg:hidden"><ThemeToggle /><button type="button" onClick={() => setOpen(!open)} className="grid h-9 w-9 place-items-center rounded-lg border border-cyan-300/20 text-cyan-200 transition hover:bg-cyan-400/10" aria-expanded={open} aria-label="Toggle navigation"><Icon name={open ? 'close' : 'menu'} size={18} /></button></div></nav>{open && <div className="border-t border-cyan-300/10 bg-[#080d24]/98 px-5 py-3 backdrop-blur-xl lg:hidden">{links.map(([to, label, icon]) => <NavLink key={to} onClick={() => { if (to === '/') handleHome(); setOpen(false) }} to={to} className={({ isActive }) => `flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${isActive ? 'bg-cyan-400/10 text-cyan-200' : 'text-slate-300 hover:bg-white/5'}`}><Icon name={icon} size={16} />{label}</NavLink>)}</div>}</header>
}
